name: 🚀 Deploy website - Hostinger
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🎉 Deploy the website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSER }}
        password: ${{ secrets.FTPPASSWORD }}
        local-dir: ./
        server-dir: ./